### ISSUE TITLE
Multi-line arg issue

### ISSUE THREAD

**Issue by jmordica** [shimaore/esl-lite#1]
Hey there! Great module!

We have an issue where sending a multi-line string (with \n at the end of each line) as an arg to the set application using command_uuid isn't working. When freeswitch logs the EXECUTE `set` it only shows the first line passed in. However, when enabling debug logs in the esl-lite lib, we can see that the library is actually passing in the multi-line arg properly. For context, we are sending a mime body type (xml body) like this `sip_multipart=[content-type]:[your data]`.

Also, enabling the debug logs in fs_cli shows that fs is only receiving the first line as well.

I noticed also this https://github.com/shimaore/esl-lite/blob/main/src/response.ts#L185 could be the solution.

Let me know if you feel like we are doing something wrong here.

Thanks!

**Comment by jmordica** [comment]
Hey @shimaore, any thoughts on the this?

Thanks!

**Comment by stephane-alnet** [comment]
@jmordica have a look at version 3.1.1, `command_uuid` should now support a multi-line argument, let me know 🙆🏻‍♂️

**Comment by jmordica** [comment]
Woohoo thank you!
